server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    #表示是否将自己注册进Eurekaserver默认为true。
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka


ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
logging:
  level:
    com.ish.springcloud.service.PaymentFeignService: debug
